name: filebot
version: 4.7~snap2
summary: The ultimate TV and Movie Renamer / Subtitle Downloader
description: FileBot is the ultimate tool for renaming your movies, tv shows or anime and even downloading subtitles. It's smart, streamlined for simplicity and just works. Putting the super-efficient UI aside, it's also got a full-featured command-line interface and scripting engine for all sorts of automation. Anything is possible.

confinement: strict

architectures: [amd64]

apps:
  filebot:
    command: desktop-launch $SNAP/filebot/filebot.sh
    plugs: [unity7, opengl, gsettings, home, x11, network, network-bind, pulseaudio]

parts:
  filebot:
    plugin: copy
    files:
      filebot.sh: filebot/filebot.sh
      FileBot.jar: filebot/FileBot.jar
      lib7-Zip-JBinding.so: filebot/lib/amd64/lib7-Zip-JBinding.so
  oracle-java:
    plugin: copy
    files:
      oracle-java: oracle-java
  packages:
    plugin: nil
    stage-packages: [jayatana]
    after: [desktop/gtk2]
