set PATH=%PATH%;"C:\Program Files\7-Zip";"C:\Program Files\FileBot";"C:\Windows\System32";"C:\Windows\System32\WindowsPowerShell\v1.0"
set AMC_PATH="C:\Users\AkshayKumar\Desktop\Torrent_Work\ut_config\filebot_scripts\scripts-master\amc.groovy"
set REPLACE_PATH="C:\Users\AkshayKumar\Desktop\Torrent_Work\ut_config\filebot_scripts\scripts-master\replace.groovy"
set CLEANER_PATH="C:\Users\AkshayKumar\Desktop\Torrent_Work\ut_config\filebot_scripts\scripts-master\customcleaner.groovy"
set MEDIA=G:/Media1
set PUSHBULLET_API_TOKEN=o.hPQwUc0iauq8BzOFsArEXe8QLphYI9SS
set PLEX_URL=localhost
set EXCLUDE_LIST=amc-input.txt
set TV=TV Shows
set FILM=New Films
set MUSIC=Music
set ANIME=Anime
set UNSORTED=Unsorted
rem set SERIES_FORMAT={n}/{'S'+s}/{fn}
set SERIES_FORMAT={n}/Season {s.pad(2)}/{n} - {s00e00} - {t}
set ANIME_FORMAT={n} - {s00e00} - {t}
set MOVIE_FORMAT={n} ({y})/{fn}
set MUSIC_FORMAT={n}/{album+'/'}{pi.pad(2)+'. '}{artist} - {t}
set CURRENT_DIRECTORY=C:/Users/AkshayKumar/Desktop/Torrent_Work/ut_config
set UNSORTED_FORMAT={file.structurePathTail}
set USER_NAME="akki007.singh@gmail.com"
set PASSWORD="buaqiwkledbcgjio"
set EMAIL_TO="akki007.singh@gmail.com"
